// Generated by https://quicktype.io

export interface APIResponse {
    _id:   string;
    uid:   string;
    Songs: Song[];
    __v:   number;
}

export interface Song {
    _id:       string;
    parsedUrl: string;
    name:      string;
    thumb:     string;
    VideoURL:  string;
}
