name: Build


on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  export:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 12.x

      - name: install depends and buld
        run: yarn && yarn export
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: Bundle
          path: __sapper__/export
  yeetToPages:
    runs-on: ubuntu-latest
    needs: [export]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          ref: gh-pages
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: Bundle
      - name: ls
        run: ls -R
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          # Arguments for the git add command
          add: .
          # The name of the user that will be displayed as the author of the commit
          author_name: Actions
          ref: gh-pages
  publish-tauri:
     strategy:
       fail-fast: false
       matrix:
         platform: [macos-latest, ubuntu-latest, windows-latest]

     runs-on: ${{ matrix.platform }}
     steps:
     - uses: actions/checkout@v2
     - name: setup node
       uses: actions/setup-node@v1
       with:
         node-version: 12
     - name: install Rust stable
       uses: actions-rs/toolchain@v1
       with:
         toolchain: stable
     - name: install tauri bundler
       run: cargo install tauri-bundler --force
     - name: install webkit2gtk (ubuntu only)
       if: matrix.platform == 'ubuntu-latest'
       run: |
         sudo apt-get update
         sudo apt-get install -y webkit2gtk-4.0
     - name: install app dependencies and build it
       run: yarn && yarn export
     - uses: tauri-apps/tauri-action@v0
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
         releaseName: "App v__VERSION__"
         body: "See the assets to download this version and install."
         draft: true
         prerelease: false
