name: Build


on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 12.x

      - name: Yarn install
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: install
    
      - name: Sapper export
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: export  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: Bundle
          path: __sapper__/export
